# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRGCJq-sjs9RnYr9nyKOHKf0JNCyba03
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

"""<h2>1- Chargement du model final </h2>"""

model_path = "final_heart_disease_model.pkl"
model = joblib.load(model_path)

"""<h2>2- Titre de l'application </h2>"""

st.title("Prédiction du Risque de Maladie Cardiaque")
st.write("Cette application Utilise un modele de ML pour prédire la probabilité du Risque")

"""<h2>3- Entrée Des Données Utilisateur </h2>"""

st.sidebar.header("Parametres d'entree")
def user_input_features():
    age = st.sidebar.slider("Âge", 18, 100, 50)
    sex = st.sidebar.selectbox("Sexe", [0, 1])
    cp = st.sidebar.selectbox("Type de douleur thoracique (cp)", [0, 1, 2, 3])
    trestbps = st.sidebar.slider("Pression artérielle au repos (trestbps)", 80, 200, 130)
    chol = st.sidebar.slider("Cholestérol (chol)", 100, 600, 240)
    fbs = st.sidebar.selectbox("Glycémie à jeun > 120 mg/dl (fbs)", [0, 1])
    restecg = st.sidebar.selectbox("Électrocardiogramme (restecg)", [0, 1, 2])
    thalach = st.sidebar.slider("Fréquence cardiaque maximale (thalach)", 50, 250, 150)
    exang = st.sidebar.selectbox("Angine induite par l'exercice (exang)", [0, 1])
    oldpeak = st.sidebar.slider("Dépression ST (oldpeak)", 0.0, 6.5, 1.0)
    slope = st.sidebar.selectbox("Pente du segment ST (slope)", [0, 1, 2])
    ca = st.sidebar.selectbox("Nombre de vaisseaux colorés (ca)", [0, 1, 2, 3, 4])
    thal = st.sidebar.selectbox("Thalassemia (thal)", [0, 1, 2, 3])

    data = {
        'age': age,
        'sex': sex,
        'cp': cp,
        'trestbps': trestbps,
        'chol': chol,
        'fbs': fbs,
        'restecg': restecg,
        'thalach': thalach,
        'exang': exang,
        'oldpeak': oldpeak,
        'slope': slope,
        'ca': ca,
        'thal': thal
    }
    return pd.DataFrame(data, index=[0])

user_data = user_input_features()
st.subheader("Données de l'utilisateur")
st.write(user_data)

"""<h2>4- Prediction En Temps Reel </h2>"""

prediction = model.predict(user_data)[0]
prediction_proba = model.predict_proba(user_data)[0][1]

st.subheader("Résultat de la Prédiction")
if prediction == 1:
    st.error(f"Risque de Maladie Cardiaque détecté: {prediction_proba:.2f}")
else:
    st.success("Pas de Risque détecté: ")
print(f"Prediction: {prediction}")
print(f"Prediction Probability: {prediction_proba}")

"""<h2>5- Visualisation Des Tendances </h2>"""

st.subheader("Analyse des tendances (Données Heart Disease)")
uploaded_data = st.file_uploader("Importer le dataset nettoyé (heart_clean.csv)", type=["csv"])

if uploaded_data is not None:
    df = pd.read_csv(uploaded_data)

    st.write("Aperçu des données :")
    st.dataframe(df.head())

    # Histogrammes
    st.write("### Histogramme des variables importantes")
    fig, ax = plt.subplots(figsize=(10,5))
    df['age'].hist(bins=20, ax=ax)
    ax.set_title("Distribution de l'âge")
    st.pyplot(fig)

    # Heatmap
    st.write("### Matrice de corrélation")
    fig, ax = plt.subplots(figsize=(10,6))
    sns.heatmap(df.corr(), annot=False, cmap="coolwarm")
    st.pyplot(fig)

    # Boxplot
    st.write("### Comparaison âge selon la maladie")
    fig, ax = plt.subplots(figsize=(8,5))
    sns.boxplot(x='target', y='age', data=df, ax=ax)
    st.pyplot(fig)

!pip install streamlit pyngrok

from pyngrok import ngrok
public_url = ngrok.connect(port='8000')
public_url