# -*- coding: utf-8 -*-
"""05_unsupervised_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llHIBIzvjMoIei9WuJLu8JPzoExzgmt6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage

"""<h2>1- Chargement de données </h2>"""

df = pd.read_csv("heart_clened.csv")
df.head()

"""<h2>2- Préparation de Données Pour Clustering </h2>"""

data = df.copy()
if "target" in data.columns:
  data_features = data.drop("target", axis=1)
else:
  data_features = data.copy()
data_features.head()

"""<h2> --> K-Means + Methode de Coude (Elbow method) </h2>"""

inertias = []
K_range = range(2, 11)
for k in K_range:
    km = KMeans(n_clusters=k, random_state=42)
    km.fit(data_features)
    inertias.append(km.inertia_)

# Visualisation
plt.figure(figsize=(8,5))
plt.plot(K_range, inertias, marker='o')
plt.title("Méthode du coude - Choix optimal de K")
plt.xlabel("Nombre de clusters (K)")
plt.ylabel("Inertie")
plt.grid(True)
plt.show()

k_optimal = 3
kmeans = KMeans(n_clusters=k_optimal, random_state=42)
clusters_kmeans = kmeans.fit_predict(data_features)
df["cluster_kmeans"] = clusters_kmeans
df.head()

"""<h2> --> Visualisation 2D </h2>"""

from sklearn.decomposition import PCA

# Perform PCA to reduce dimensionality for visualization
pca = PCA(n_components=2)
pca_components = pca.fit_transform(data_features)

# Add PCA components to the DataFrame
df['pca1'] = pca_components[:, 0]
df['pca2'] = pca_components[:, 1]

plt.figure(figsize=(8,6))
sns.scatterplot(
    x=df["pca1"],
    y=df["pca2"],
    hue=df["cluster_kmeans"],
    palette="Set2"
)
plt.title("Clustering K-Means (Projection PCA)")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.show()

"""<h2> --> Score Sihouette </h2>"""

sil_kmeans = silhouette_score(data_features, clusters_kmeans)
sil_kmeans

"""<h2> --> Regroupement Hierarchique </h2>"""

plt.figure(figsize=(12,6))
Z = linkage(data_features, method="ward")
dendrogram(Z, truncate_mode="level", p=5)
plt.title("Dendrogramme - Clustering hiérarchique")
plt.xlabel("Observations")
plt.ylabel("Distance")
plt.show()

agg = AgglomerativeClustering(n_clusters=3, linkage="ward")
clusters_hier = agg.fit_predict(data_features)
df["cluster_hier"] = clusters_hier
df.head()

"""<h2>--> Visualisation </h2>"""

plt.figure(figsize=(8,6))
sns.scatterplot(
    x=df["pca1"],
    y=df["pca2"],
    hue=df["cluster_hier"],
    palette="Set1"
)
plt.title("Clustering Hiérarchique (Projection PCA)")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.show()

"""<h2>--> Comparaison avec les Vraies étiquettes

*/ Comparaison sous format de tableau croisé
"""

if "target" in df.columns:
    print("Comparaison K-Means vs Vérité :")
    print(pd.crosstab(df["target"], df["cluster_kmeans"]))

    print("\nComparaison Hierarchical vs Vérité :")
    print(pd.crosstab(df["target"], df["cluster_hier"]))

"""*/ Scores silhouette"""

sil_hier = silhouette_score(data_features, clusters_hier)

print("Silhouette KMeans :", sil_kmeans)
print("Silhouette Hierarchical :", sil_hier)

"""<h2> Export Données </h2>"""

df.to_csv("heart_clustering_results.csv", index=False)
print("Fichier exporté : heart_clustering_results.csv")